name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build VitePress site
        run: |
          pnpm run docs:build || (echo "构建失败，查看日志:" && cat .vitepress/dist/.temp/build.log && exit 1)
        continue-on-error: true  # 允许步骤失败，继续执行后续步骤以获取更多信息

      - name: Debug build output
        run: |
          echo "当前目录结构:"
          ls -al
          echo "检查 .vitepress 目录:"
          ls -al .vitepress || echo ".vitepress 目录不存在"
          echo "检查 package.json 中的构建脚本:"
          cat package.json | grep scripts -A 5
        if: always()  # 总是执行此步骤，无论前面是否失败

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vitepress/dist
          force_orphan: true
        if: success()  # 仅当构建成功时执行部署